version: '3.9'
services:
  api:
    image: 'prioarief/furnifinder-api:latest'
    restart: 'always'
    container_name: 'api'
    ports:
      - '7777:7777'
    environment:
      - NODE_ENV=
      - APP_PORT=
      - MONGODB_CONNECTION_URL=
      - SENTRY_DSN=
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=